version: '3.8'

services:
  postgres:
    image: postgres:16 # Use the latest stable version
    container_name: bazaarbd_postgres
    restart: always
    ports:
      - '5432:5432' # Maps container's 5432 port to local 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9223
      POSTGRES_DB: bazaarbd_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
